tls:
  certificates:
    - certFile: /vault/secrets/certs/fullchain.crt  # Desde tmpfs del Shared Vault Agent
      keyFile: /vault/secrets/certs/server.key     # Certificados en memoria encriptada
  stores:
    default:
      defaultCertificate:
        certFile: /vault/secrets/certs/fullchain.crt
        keyFile: /vault/secrets/certs/server.key