---
global:
  checkNewVersion: true
  sendAnonymousUsage: false

log:
  level: DEBUG
  #filePath: "/var/log/traefik/traefik.log"
  format: json

accesslog:
  filePath: "/var/log/traefik/access.log"
  bufferingSize: 100
  format: json
  filters:
    statusCodes:
      - "400-499"
      - "500-599"

api:
  dashboard: true
  insecure: false

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443
    http:
      middlewares:
        - "security-headers@file"
  metrics:
    address: :9090

# certificatesResolvers - comentado para usar certificados locales
# certificatesResolvers:
#   cloudflare:
#     acme:
#       email: xxxxxx.xxxxx@gmail.com
#       storage: /var/traefik/certs/cloudflare-acme.json
#       caServer: "https://acme-v02.api.letsencrypt.org/directory"
#       dnsChallenge:
#         provider: cloudflare
#         delayBeforeCheck: "30"
#         resolvers:
#           - "1.1.1.1:53"
#           - "8.8.8.8:53"

providers:
  docker:
    endpoint: "tcp://socket-proxy:2375"
    exposedByDefault: false
    network: frontend

  file:
    directory: /etc/traefik
    watch: true

ping:
  entryPoint: web

metrics:
  prometheus:
    entryPoint: metrics
    addEntryPointsLabels: true
    addServicesLabels: true
    buckets: [0.1,0.3,0.5,1.2,5.0]
